name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy
        run: |
          git fetch origin gh-pages --depth=1
          git worktree add ..//gh-pages gh-pages --no-checkout
          cp -rT build/ ../gh-pages
          cd ../gh-pages
          git add --all .
          git commit -m "Deploy"
          git push origin gh-pages